import { type NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import MainBody from "../components/MainBody/MainBody";

const Home: NextPage = () => {
  return (
    <div className="h-sreen flex flex-col items-center justify-center">
      <Head>
        <title>Google 2.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b">
        <MainBody />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
